### ISSUE TITLE
run inference_eval.py error

### ISSUE THREAD

**Issue by Jail0910** [Mingxiao-Li/Animate-Your-Motion#3]
/home/adt/01_learn/Animate-Your-Motion/inference_eval.py:32 in <module>                          │
│                                                                                                  │
│    29 # from transformers import CLIPTokenizer                                                   │
│    30 from text_grounding_input import GroundingNetInput                                         │
│    31 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline                           │
│ ❱  32 from train import Trainer                                                                  │
│    33 from modelscope_t2v.text_to_video_synthesis_model import get_model_scope_t2v_models        │
│    34 from util import save_videos_grid,draw_boxes,visual_img                                    │
│    35 from data.concate_dataset import CatObjTrackVideoDataset, collate_fn                       │
│                                                                                                  │
│ /home/adt/01_learn/Animate-Your-Motion/train.py:10 in <module>                                   │
│                                                                                                  │
│     7                                                                                            │
│     8 from tqdm.auto import tqdm                                                                 │
│     9 from einops import rearrange                                                               │
│ ❱  10 from pipelines import VideoGenerationPipeline                                              │
│    11 from util import save_videos_grid, generate_pos_coords, generate_frame_mask                │
│    12 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline                           │
│    13 from text_grounding_input import GroundingNetInput                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'pipelines'

I found that Trainer was not used, so I commented it out, but a new problem occurred！！！

 /home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/text_to_video_synthesis_model.py:15 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    12 from modelscope_t2v.diffusion import GaussianDiffusion, beta_schedule                      │
│    13 from modelscope_t2v.unet_sd import UNetSD                                                  │
│    14 from modelscope_t2v.config import Config                                                   │
│ ❱  15 from models.position_net import PositionNet                                                │
│    16 from modelscope_t2v.controlnet import ControlNet                                           │
│    17                                                                                            │
│    18                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'models'

**Comment by Mingxiao-Li** [comment]
thanks for your questions, we will look into it today.

**Comment by Mingxiao-Li** [comment]
> /home/adt/01_learn/Animate-Your-Motion/inference_eval.py:32 in │ │ │ │ 29 # from transformers import CLIPTokenizer │ │ 30 from text_grounding_input import GroundingNetInput │ │ 31 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline │ │ ❱ 32 from train import Trainer │ │ 33 from modelscope_t2v.text_to_video_synthesis_model import get_model_scope_t2v_models │ │ 34 from util import save_videos_grid,draw_boxes,visual_img │ │ 35 from data.concate_dataset import CatObjTrackVideoDataset, collate_fn │ │ │ │ /home/adt/01_learn/Animate-Your-Motion/train.py:10 in │ │ │ │ 7 │ │ 8 from tqdm.auto import tqdm │ │ 9 from einops import rearrange │ │ ❱ 10 from pipelines import VideoGenerationPipeline │ │ 11 from util import save_videos_grid, generate_pos_coords, generate_frame_mask │ │ 12 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline │ │ 13 from text_grounding_input import GroundingNetInput │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ ModuleNotFoundError: No module named 'pipelines'
> 
> I found that Trainer was not used, so I commented it out, but a new problem occurred！！！
> 
> /home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/text_to_video_synthesis_model.py:15 in │ │ │ │ │ │ 12 from modelscope_t2v.diffusion import GaussianDiffusion, beta_schedule │ │ 13 from modelscope_t2v.unet_sd import UNetSD │ │ 14 from modelscope_t2v.config import Config │ │ ❱ 15 from models.position_net import PositionNet │ │ 16 from modelscope_t2v.controlnet import ControlNet │ │ 17 │ │ 18 │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ ModuleNotFoundError: No module named 'models'

thanks for your questions, we will look into it today.

**Comment by Jail0910** [comment]
你好我已经收到你的邮件，我会尽快回复，谢谢！姜建宇

**Comment by Mingxiao-Li** [comment]
> /home/adt/01_learn/Animate-Your-Motion/inference_eval.py:32 in │ │ │ │ 29 # from transformers import CLIPTokenizer │ │ 30 from text_grounding_input import GroundingNetInput │ │ 31 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline │ │ ❱ 32 from train import Trainer │ │ 33 from modelscope_t2v.text_to_video_synthesis_model import get_model_scope_t2v_models │ │ 34 from util import save_videos_grid,draw_boxes,visual_img │ │ 35 from data.concate_dataset import CatObjTrackVideoDataset, collate_fn │ │ │ │ /home/adt/01_learn/Animate-Your-Motion/train.py:10 in │ │ │ │ 7 │ │ 8 from tqdm.auto import tqdm │ │ 9 from einops import rearrange │ │ ❱ 10 from pipelines import VideoGenerationPipeline │ │ 11 from util import save_videos_grid, generate_pos_coords, generate_frame_mask │ │ 12 from modelscope_t2v.ms_pipeline import MSVideoGenerationPipeline │ │ 13 from text_grounding_input import GroundingNetInput │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ ModuleNotFoundError: No module named 'pipelines'
> 
> I found that Trainer was not used, so I commented it out, but a new problem occurred！！！
> 
> /home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/text_to_video_synthesis_model.py:15 in │ │ │ │ │ │ 12 from modelscope_t2v.diffusion import GaussianDiffusion, beta_schedule │ │ 13 from modelscope_t2v.unet_sd import UNetSD │ │ 14 from modelscope_t2v.config import Config │ │ ❱ 15 from models.position_net import PositionNet │ │ 16 from modelscope_t2v.controlnet import ControlNet │ │ 17 │ │ 18 │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ ModuleNotFoundError: No module named 'models'

hi， we have fixed the bugs, could you pull it and try again ? It should work now.

**Comment by Jail0910** [comment]
**I pull and run, It prompts me that there is no configuration.json file，I use got10k**

Traceback (most recent call last):
  File "/home/adt/01_learn/Animate-Your-Motion/inference_eval.py", line 360, in <module>
    main(**config)
  File "/home/adt/01_learn/Animate-Your-Motion/inference_eval.py", line 75, in main
    unet, vae, text_encoder, diffusion, position_net, visual_encoder, controlnet_encoder = get_model_scope_t2v_models(
  File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/text_to_video_synthesis_model.py", line 424, in get_model_scope_t2v_models
    config = Config.from_file(
  File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/config.py", line 108, in from_file
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/config.py", line 115, in _file2dict
    raise ValueError(f'File does not exists {filename}')
ValueError: File does not exists /media/adt/jjy_data/GOT-10k/dataset/configuration.json

**Comment by Jail0910** [comment]
my dataset folder structure

dataset/
├── got10k_val_caption.json
├── obj_embedding.json
└── val
    ├── GOT-10k_Val_000001
    ├── GOT-10k_Val_000002
    ├── GOT-10k_Val_000003
    ├── GOT-10k_Val_000004
    ├── GOT-10k_Val_000005
    ├── GOT-10k_Val_000006
    ├── GOT-10k_Val_000007
    ├── GOT-10k_Val_000008
    ├── GOT-10k_Val_000009
    ├── GOT-10k_Val_000010
    ├── GOT-10k_Val_000011
    ├── GOT-10k_Val_000012
    ├── GOT-10k_Val_000013
    ├── GOT-10k_Val_000014
    ├── GOT-10k_Val_000015
    ├── GOT-10k_Val_000016
    ├── GOT-10k_Val_000017
    ├── GOT-10k_Val_000018
    ├── GOT-10k_Val_000019
    ├── GOT-10k_Val_000020
    ├── GOT-10k_Val_000021
    ├── GOT-10k_Val_000022
    ├── GOT-10k_Val_000023
    ├── GOT-10k_Val_000024
    ├── GOT-10k_Val_000025
    ├── GOT-10k_Val_000026
    ├── GOT-10k_Val_000027
    ├── GOT-10k_Val_000028
    ├── GOT-10k_Val_000029
    ├── GOT-10k_Val_000030
    ├── GOT-10k_Val_000031
    ├── GOT-10k_Val_000032
    ├── GOT-10k_Val_000033
    ├── GOT-10k_Val_000034
    ├── GOT-10k_Val_000035
    ├── GOT-10k_Val_000036
    ├── GOT-10k_Val_000037
    ├── GOT-10k_Val_000038
    ├── GOT-10k_Val_000039
    ├── GOT-10k_Val_000040
    ├── GOT-10k_Val_000041
    ├── GOT-10k_Val_000042
    ├── GOT-10k_Val_000043
    ├── GOT-10k_Val_000044
    ├── GOT-10k_Val_000045
    ├── GOT-10k_Val_000046
    ├── GOT-10k_Val_000047
    ├── GOT-10k_Val_000048
    ├── GOT-10k_Val_000049
    ├── GOT-10k_Val_000050
    ├── GOT-10k_Val_000051
    ├── GOT-10k_Val_000052
    ├── GOT-10k_Val_000053
    ├── GOT-10k_Val_000054
    ├── GOT-10k_Val_000055
    ├── GOT-10k_Val_000056
    ├── GOT-10k_Val_000057
    ├── GOT-10k_Val_000058
    ├── GOT-10k_Val_000059
    ├── GOT-10k_Val_000060
    ├── GOT-10k_Val_000061
    ├── GOT-10k_Val_000062
    ├── GOT-10k_Val_000063
    ├── GOT-10k_Val_000064
    ├── GOT-10k_Val_000065
    ├── GOT-10k_Val_000066
    ├── GOT-10k_Val_000067
    ├── GOT-10k_Val_000068
    ├── GOT-10k_Val_000069
    ├── GOT-10k_Val_000070
    ├── GOT-10k_Val_000071
    ├── GOT-10k_Val_000072
    ├── GOT-10k_Val_000073
    ├── GOT-10k_Val_000074
    ├── GOT-10k_Val_000075
    ├── GOT-10k_Val_000076
    ├── GOT-10k_Val_000077
    ├── GOT-10k_Val_000078
    ├── GOT-10k_Val_000079
    ├── GOT-10k_Val_000080
    ├── GOT-10k_Val_000081
    ├── GOT-10k_Val_000082
    ├── GOT-10k_Val_000083
    ├── GOT-10k_Val_000084
    ├── GOT-10k_Val_000085
    ├── GOT-10k_Val_000086
    ├── GOT-10k_Val_000087
    ├── GOT-10k_Val_000088
    ├── GOT-10k_Val_000089
    ├── GOT-10k_Val_000090
    ├── GOT-10k_Val_000091
    ├── GOT-10k_Val_000092
    ├── GOT-10k_Val_000093
    ├── GOT-10k_Val_000094
    ├── GOT-10k_Val_000095
    ├── GOT-10k_Val_000096
    ├── GOT-10k_Val_000097
    ├── GOT-10k_Val_000098
    ├── GOT-10k_Val_000099
    ├── GOT-10k_Val_000100
    ├── GOT-10k_Val_000101
    ├── GOT-10k_Val_000102
    ├── GOT-10k_Val_000103
    ├── GOT-10k_Val_000104
    ├── GOT-10k_Val_000105
    ├── GOT-10k_Val_000106
    ├── GOT-10k_Val_000107
    ├── GOT-10k_Val_000108
    ├── GOT-10k_Val_000109
    ├── GOT-10k_Val_000110
    ├── GOT-10k_Val_000111
    ├── GOT-10k_Val_000112
    ├── GOT-10k_Val_000113
    ├── GOT-10k_Val_000114
    ├── GOT-10k_Val_000115
    ├── GOT-10k_Val_000116
    ├── GOT-10k_Val_000117
    ├── GOT-10k_Val_000118
    ├── GOT-10k_Val_000119
    ├── GOT-10k_Val_000120
    ├── GOT-10k_Val_000121
    ├── GOT-10k_Val_000122
    ├── GOT-10k_Val_000123
    ├── GOT-10k_Val_000124
    ├── GOT-10k_Val_000125
    ├── GOT-10k_Val_000126
    ├── GOT-10k_Val_000127
    ├── GOT-10k_Val_000128
    ├── GOT-10k_Val_000129
    ├── GOT-10k_Val_000130
    ├── GOT-10k_Val_000131
    ├── GOT-10k_Val_000132
    ├── GOT-10k_Val_000133
    ├── GOT-10k_Val_000134
    ├── GOT-10k_Val_000135
    ├── GOT-10k_Val_000136
    ├── GOT-10k_Val_000137
    ├── GOT-10k_Val_000138
    ├── GOT-10k_Val_000139
    ├── GOT-10k_Val_000140
    ├── GOT-10k_Val_000141
    ├── GOT-10k_Val_000142
    ├── GOT-10k_Val_000143
    ├── GOT-10k_Val_000144
    ├── GOT-10k_Val_000145
    ├── GOT-10k_Val_000146
    ├── GOT-10k_Val_000147
    ├── GOT-10k_Val_000148
    ├── GOT-10k_Val_000149
    ├── GOT-10k_Val_000150
    ├── GOT-10k_Val_000151
    ├── GOT-10k_Val_000152
    ├── GOT-10k_Val_000153
    ├── GOT-10k_Val_000154
    ├── GOT-10k_Val_000155
    ├── GOT-10k_Val_000156
    ├── GOT-10k_Val_000157
    ├── GOT-10k_Val_000158
    ├── GOT-10k_Val_000159
    ├── GOT-10k_Val_000160
    ├── GOT-10k_Val_000161
    ├── GOT-10k_Val_000162
    ├── GOT-10k_Val_000163
    ├── GOT-10k_Val_000164
    ├── GOT-10k_Val_000165
    ├── GOT-10k_Val_000166
    ├── GOT-10k_Val_000167
    ├── GOT-10k_Val_000168
    ├── GOT-10k_Val_000169
    ├── GOT-10k_Val_000170
    ├── GOT-10k_Val_000171
    ├── GOT-10k_Val_000172
    ├── GOT-10k_Val_000173
    ├── GOT-10k_Val_000174
    ├── GOT-10k_Val_000175
    ├── GOT-10k_Val_000176
    ├── GOT-10k_Val_000177
    ├── GOT-10k_Val_000178
    ├── GOT-10k_Val_000179
    ├── GOT-10k_Val_000180
    └── list.txt

**Comment by Mingxiao-Li** [comment]
> **I pull and run, It prompts me that there is no configuration.json file，I use got10k**
> 
> Traceback (most recent call last): File "/home/adt/01_learn/Animate-Your-Motion/inference_eval.py", line 360, in main(**config) File "/home/adt/01_learn/Animate-Your-Motion/inference_eval.py", line 75, in main unet, vae, text_encoder, diffusion, position_net, visual_encoder, controlnet_encoder = get_model_scope_t2v_models( File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/text_to_video_synthesis_model.py", line 424, in get_model_scope_t2v_models config = Config.from_file( File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/config.py", line 108, in from_file cfg_dict, cfg_text = Config._file2dict(filename) File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/config.py", line 115, in _file2dict raise ValueError(f'File does not exists {filename}') ValueError: File does not exists /media/adt/jjy_data/GOT-10k/dataset/configuration.json

could you post the bash script you used to run the code ?
the configuration file for evaluation is saved in the configs folder  configs/object_tracking_eval.yaml

**Comment by Jail0910** [comment]
I don't know what root_path refers to, and the configuration.json, and the text2video_pytorch_model.pth, I am not find in 
[Hugging Face](https://huggingface.co/)

    config = Config.from_file(
        os.path.join(cfg_root_path, "configuration.json")
    )

    if pretrained_weight_path is None:
        pretrained_weight_path = os.path.join(cfg_root_path, "text2video_pytorch_model.pth")
        pretrained_weights_dict = torch.load(
               pretrained_weight_path
            )
    else:
        pretrained_weights_dict = torch.load(pretrained_weight_path)

**Comment by Mingxiao-Li** [comment]
> I don't know what root_path refers to, and the configuration.json, and the text2video_pytorch_model.pth, I am not find in [Hugging Face](https://huggingface.co/)
> 
> ```
> config = Config.from_file(
>     os.path.join(cfg_root_path, "configuration.json")
> )
> 
> if pretrained_weight_path is None:
>     pretrained_weight_path = os.path.join(cfg_root_path, "text2video_pytorch_model.pth")
>     pretrained_weights_dict = torch.load(
>            pretrained_weight_path
>         )
> else:
>     pretrained_weights_dict = torch.load(pretrained_weight_path)
> ```

the root path refers to the original pretrained model-scope  text-to-video folder

**Comment by Jail0910** [comment]
**this is the yaml file**
pretrained_model_path: "./stable-diffusion-v1-4"
root_path: "/home/adt/01_learn/Animate-Your-Motion"

eval_data:
  name: object_tracking
  path: "/media/adt/jjy_data/GOT-10k/dataset"
  datasets:
    - "got10k"
  n_sample_frames: 8 
  width: 256
  height: 256
  split: "val"
  num_max_obj: 8


seed: 33
mixed_precision: fp16
enable_xformers_memory_efficient_attention: True

**my bash script is** 
accelerate launch inference_eval.py --config ./configs/object_tracking_eval_t.yaml --video_length 8 --train_grounding vanilla_cross_vision --trained_ckpt_path ./weight/ --cross_vision --dataset got10k --output_dir /media/adt/jjy_data/GOT-10k/out --batch_size 1 --cat_init

**Comment by Mingxiao-Li** [comment]
> **this is the yaml file** pretrained_model_path: "./stable-diffusion-v1-4" root_path: "/home/adt/01_learn/Animate-Your-Motion"
> 
> eval_data: name: object_tracking path: "/media/adt/jjy_data/GOT-10k/dataset" datasets: - "got10k" n_sample_frames: 8 width: 256 height: 256 split: "val" num_max_obj: 8
> 
> seed: 33 mixed_precision: fp16 enable_xformers_memory_efficient_attention: True
> 
> **my bash script is** accelerate launch inference_eval.py --config ./configs/object_tracking_eval_t.yaml --video_length 8 --train_grounding vanilla_cross_vision --trained_ckpt_path ./weight/ --cross_vision --dataset got10k --output_dir /media/adt/jjy_data/GOT-10k/out --batch_size 1 --cat_init

the root path should refer to the pretrained model-scope text to video folder. you can download it from https://huggingface.co/ali-vilab/modelscope-damo-text-to-video-synthesis/tree/main

**Comment by Jail0910** [comment]
> > **this is the yaml file** pretrained_model_path: "./stable-diffusion-v1-4" root_path: "/home/adt/01_learn/Animate-Your-Motion"
> > eval_data: name: object_tracking path: "/media/adt/jjy_data/GOT-10k/dataset" datasets: - "got10k" n_sample_frames: 8 width: 256 height: 256 split: "val" num_max_obj: 8
> > seed: 33 mixed_precision: fp16 enable_xformers_memory_efficient_attention: True
> > **my bash script is** accelerate launch inference_eval.py --config ./configs/object_tracking_eval_t.yaml --video_length 8 --train_grounding vanilla_cross_vision --trained_ckpt_path ./weight/ --cross_vision --dataset got10k --output_dir /media/adt/jjy_data/GOT-10k/out --batch_size 1 --cat_init
> 
> the root path should refer to the pretrained model-scope text to video folder. you can download it from https://huggingface.co/ali-vilab/modelscope-damo-text-to-video-synthesis/tree/main

**think you, I run it sucessful**
