### ISSUE TITLE
run inference_customize.py error

### ISSUE THREAD

**Issue by Jail0910** [Mingxiao-Li/Animate-Your-Motion#5]
I try to run inference_customize.py but error
Traceback (most recent call last):
  File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 304, in <module>
    main(**config)
  File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 244, in main
    output = pipeline(
  File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/ms_pipeline.py", line 123, in __call__
    grounding_context = self.position_net(
  File "/home/adt/anaconda3/envs/st2v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/adt/01_learn/Animate-Your-Motion/models/position_net.py", line 55, in forward
    positive_embeddings = positive_embeddings*masks + (1-masks)*positive_null
RuntimeError: The size of tensor a (8192) must match the size of tensor b (1024) at non-singleton dimension 2

I build a image and a txt, the contents of txt is, only one line
952.0000,383.0000,1244.0000,625.0000

**Comment by Mingxiao-Li** [comment]
> I try to run inference_customize.py but error Traceback (most recent call last): File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 304, in main(**config) File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 244, in main output = pipeline( File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/ms_pipeline.py", line 123, in **call** grounding_context = self.position_net( File "/home/adt/anaconda3/envs/st2v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(_args, **kwargs) File "/home/adt/01_learn/Animate-Your-Motion/models/position_net.py", line 55, in forward positive_embeddings = positive_embeddings_masks + (1-masks)*positive_null RuntimeError: The size of tensor a (8192) must match the size of tensor b (1024) at non-singleton dimension 2
> 
> I build a image and a txt, the contents of txt is, only one line 952.0000,383.0000,1244.0000,625.0000

We will look into it this weekend.

**Comment by Mingxiao-Li** [comment]
> I try to run inference_customize.py but error Traceback (most recent call last): File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 304, in main(**config) File "/home/adt/01_learn/Animate-Your-Motion/inference_test.py", line 244, in main output = pipeline( File "/home/adt/01_learn/Animate-Your-Motion/modelscope_t2v/ms_pipeline.py", line 123, in **call** grounding_context = self.position_net( File "/home/adt/anaconda3/envs/st2v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(_args, **kwargs) File "/home/adt/01_learn/Animate-Your-Motion/models/position_net.py", line 55, in forward positive_embeddings = positive_embeddings_masks + (1-masks)*positive_null RuntimeError: The size of tensor a (8192) must match the size of tensor b (1024) at non-singleton dimension 2
> 
> I build a image and a txt, the contents of txt is, only one line 952.0000,383.0000,1244.0000,625.0000

We have fixed a small bug. In your case, the error comes from the different number of box coordinates and frames. The number of box coordinates should be the same as that of frames, as each frame is conditioned on a box coordinate. The model was trained with 8 frames, thus you need to provide a txt with 8 lines, such as : 
27.067099567099575,90.51298701298697,169.0584415584416,193.7164502164502
32.26190476190476,91.20562770562765,174.25324675324677,194.40909090909088
38.14935064935065,91.55194805194799,180.14069264069266,194.75541125541122
44.036796536796544,91.55194805194799,186.02813852813856,194.75541125541122
48.88528138528139,91.55194805194799,190.8766233766234,194.75541125541122
56.15800865800864,91.89826839826833,198.14935064935065,195.10173160173156
62.73809523809521,91.89826839826833,204.72943722943722,195.10173160173156
70.01082251082249,91.89826839826833,212.0021645021645,195.10173160173156
~
