### ISSUE TITLE
Can't find reference to ‘MyWandbTracker’ in ‘imported module trackers’. 

### ISSUE THREAD

**Issue by Namonamos** [Mingxiao-Li/Animate-Your-Motion#6]
In the ms_main.py file, I try to "pip install trackers" but it says MyWandbTracker not found, can you tell me what to do?

**Comment by Mingxiao-Li** [comment]
> In the ms_main.py file, I try to "pip install trackers" but it says MyWandbTracker not found, can you tell me what to do?

Sorry, we forgot to upload the tracker.py file. We have uploaded it, could you pull again to update your code ?

**Comment by Namonamos** [comment]
Thank you, the error is now resolved.
