### ISSUE TITLE
Unresolved reference ‘VideoGenerationPipeline’

### ISSUE THREAD

**Issue by Namonamos** [Mingxiao-Li/Animate-Your-Motion#7]
VideoGenerationPipeline is used in the train.py file, am I correct in trying to ‘pip install pipelines’?
I've been trying to install the ‘pipelines’ package for a long time, but I get an error.

**Comment by Mingxiao-Li** [comment]
> VideoGenerationPipeline is used in the train.py file, am I correct in trying to ‘pip install pipelines’? I've been trying to install the ‘pipelines’ package for a long time, but I get an error.

could you provide more information about the error you got ?

**Comment by Namonamos** [comment]
![QQ20241125-220613](https://github.com/user-attachments/assets/2cca444e-58bf-4cc6-942b-ef019b6c209c)
I downloaded ‘pipelines’ in Win and it says that sh 1.11 is not available, should I move to ubuntu and is the pipelines package necessary?

**Comment by Mingxiao-Li** [comment]
> ![QQ20241125-220613](https://private-user-images.githubusercontent.com/111292032/389558784-2cca444e-58bf-4cc6-942b-ef019b6c209c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDQyNzIsIm5iZiI6MTczMjU0Mzk3MiwicGF0aCI6Ii8xMTEyOTIwMzIvMzg5NTU4Nzg0LTJjY2E0NDRlLTU4YmYtNGNjNi05NDJiLWVmMDE5YjZjMjA5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDEyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjk1MzgzZGE2MTVlZGFkYTE4MGQ5NjRlYTBmYzc3ZDcxNThjOTEwZDg3YmViMGQ3MzJmMzVjMDhjNzBmNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XeXO9Uy9rs9V4EJcyO0_SM8Q80aO6pLVZhlGb9ndFgM) I downloaded ‘pipelines’ in Win and it says that sh 1.11 is not available, should I move to ubuntu and is the pipelines package necessary?

If you follow the instruction of creating environment using conda, then you do not need to install other package manually.
Also the video generation pipeline is implemented in  modelscope_t2v/ms_pipeline.py file, I do not think you need to install other pipeline package.

**Comment by Namonamos** [comment]
Thanks for the answer, I will check again.
